---
- gather_facts: false
  hosts: localhost
  vars_files:
    - Server_Inventory_hosts.yml
  tasks:
  - name: Create a change ticket in SNOW 
    register: new_change_request
    snow_record:
      data:
        u_environment: "{{item.Environment}}"
        short_description: "{{item.Short_Description}}"
        category: "{{item.Category}}"
      instance: dev119884
      password: gn9aZ7TKFIwa
      state: present
      table: change_request
      username: admin
    with_items:
        - "{{ serverinventory }}"
#    register: new_change_request
#- debug: var=new_change_request.record.number
